# Generated by Django 4.1.1 on 2022-09-16 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
    ]
