# Generated by Django 4.0.6 on 2022-09-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_login_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='passlog',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='userlog',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='passlist',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='userlist',
        ),
    ]
