# Generated by Django 4.1.2 on 2022-10-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_rename_passlog_login_pass_log_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
