# Generated by Django 4.1.2 on 2022-10-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
